In [1]:
import numpy as np
import pandas as pd

In [3]:
df=pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comments','campusx write comment'],'output':[1,1,0,0]})

In [4]:
df.head()

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2  people write comments       0
3  campusx write comment       0

#BOW implementation n_grams,bigrams,trigrams

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

In [15]:
cv=CountVectorizer(ngram_range=(2,2))
bow=cv.fit_transform(df['text']).toarray()

In [16]:
bow

array([[0, 0, 1, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 1],
       [0, 1, 0, 0, 0, 1, 0]])

In [17]:
cv.vocabulary_

{'people watch': 2,
 'watch campusx': 4,
 'campusx watch': 0,
 'people write': 3,
 'write comments': 6,
 'campusx write': 1,
 'write comment': 5}

#TF-IDF implementation

In [18]:
df1=pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comments','campusx write comment'],'output':[1,1,0,0]})

In [19]:
df1.head()

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2  people write comments       0
3  campusx write comment       0

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
bow1=tfidf.fit_transform(df1['text']).toarray()

In [21]:
bow1

array([[0.49681612, 0.        , 0.        , 0.61366674, 0.61366674,
        0.        ],
       [0.8508161 , 0.        , 0.        , 0.        , 0.52546357,
        0.        ],
       [0.        , 0.        , 0.66767854, 0.52640543, 0.        ,
        0.52640543],
       [0.44809973, 0.70203482, 0.        , 0.        , 0.        ,
        0.55349232]])

In [22]:
tfidf.idf_

array([1.22314355, 1.91629073, 1.91629073, 1.51082562, 1.51082562,
       1.51082562])

In [23]:
tfidf.get_feature_names_out()

array(['campusx', 'comment', 'comments', 'people', 'watch', 'write'],
      dtype=object)

#One hot encoding

In [26]:
df2=pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comments','campusx write comment'],'output':[1,1,0,0]})

In [27]:
df2.head()

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2  people write comments       0
3  campusx write comment       0

In [28]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
word_encoded=ohe.fit_transform(df2[['text']]).toarray()

In [29]:
print(word_encoded)

[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]
